# Generated by Django 4.1.1 on 2022-10-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TemplesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("history", models.CharField(max_length=10000)),
                ("darshtim", models.CharField(max_length=1000)),
                ("puja", models.CharField(max_length=1000)),
                ("food", models.CharField(max_length=1000)),
                ("income", models.CharField(max_length=1000)),
            ],
        ),
    ]
